id: P010602
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:02.327871
source_metadata:
  id: bdr:W1KG24651
  title: འདུལ་བའི་བསླབ་བྱ།
  author: ''
  volumes:
    46db5210a6344c0186cf16f6c85713e1:
      image_group_id: I1KG25040
      title: ''
      volume_number: 1
      total_pages: 494
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
